export const FarmStoreActionTypes = {
  FETCH_FARM_PRODUCE_START: "FETCH_FARM_PRODUCE_START",
  FETCH_FARM_PRODUCE_SUCCESS: "FETCH_FARM_PRODUCE_SUCCESS",
  FETCH_FARM_PRODUCE_FAILURE: "FETCH_FARM_PRODUCE_FAILURE",
};
