export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_OUT_USER: "SIGN_OUT_USER",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCESS: "EMAIL_SIGN_IN_SUCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE",
  EMAIL_SIGN_UP_START: "EMAIL_SIGN_UP_START",
  EMAIL_SIGN_UP_SUCCESS: "EMAIL_SIGN_UP_START",
  EMAIL_SIGN_UP_FAILURE: "EMAIL_SIGN_UP_START",
};
